name: pull-request
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
#        run: sudo apt-get install xvfb
      - run: yarn
      - run: yarn lint
      - run: yarn test
